<?php
session_start();
if(!isset($_SESSION['teacher_id'])) { header("Location: login.php"); exit(); }
$dept = $_SESSION['teacher_dept'];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance Report | <?php echo $dept; ?></title>
    <style><?php include('css/attendance.css'); ?></style>
</head>
<body>
    <div class="nav-bar">
        <div class="nav-logo">IOE Report Portal</div>
        <div class="nav-user">
            <a href="attendance.php" style="color: white; margin-right: 20px;">← Back to Dashboard</a>
            <span><strong><?php echo $_SESSION['teacher_name']; ?></strong></span>
        </div>
    </div>

    <div class="main-content">
        <div class="card filter-section">
            <h3 class="section-title">Generate Subject Report</h3>
            <div class="filter-grid" style="grid-template-columns: 1fr 1fr auto;">
                <div class="input-group">
                    <label>Year</label>
                    <select id="year_select">
                        <option value="">Select Year</option>
                        <option value="1">1st Year</option>
                        <option value="2">2nd Year</option>
                        <option value="3">3rd Year</option>
                        <option value="4">4th Year</option>
                    </select>
                </div>
                <div class="input-group">
                    <label>Subject</label>
                    <select id="subject_select">
                        <option value="">Select Year First</option>
                    </select>
                </div>
                <button id="generate_report_btn" class="btn-primary" style="align-self: end;">View Report</button>
            </div>
        </div>

        <div id="report_area" class="card list-section" style="display:none;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; border-bottom: 2px solid #eee; padding-bottom: 10px;">
            <div>
                <h2 id="report_title" style="margin:0; color: #1e293b;">Subject Analysis</h2>
                <p style="color: #64748b; margin-top: 5px;">Generated by: <?php echo $_SESSION['teacher_name']; ?> (<?php echo $dept; ?>)</p>
            </div>
            <button onclick="printReport()" class="btn-success" style="background: #6366f1; display: flex; align-items: center; gap: 8px;">
                <span style="font-size: 1.2rem;">⎙</span> Print Official Report
            </button>
        </div>

        <table class="attendance-table" id="printable_table">
            <thead>
                <tr>
                    <th>Roll No</th>
                    <th>Student Name</th>
                    <th>Present</th>
                    <th>Total</th>
                    <th>Percentage</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody id="report_data"></tbody>
        </table>
    </div>
    </div>

    <script src="js/jquery.js"></script>
    <script>
        $(document).ready(function() {
            // Load Subjects (Same as attendance page)
            $("#year_select").change(function() {
                $.ajax({
                    url: "ajaxhandler/attendanceAjax.php",
                    type: "POST",
                    data: { action: "get_subjects", year: $(this).val() },
                    dataType: "json",
                    success: function(data) {
                        let html = '<option value="">Select Subject</option>';
                        data.forEach(sub => html += `<option value="${sub.id}">${sub.course_name}</option>`);
                        $("#subject_select").html(html);
                    }
                });
            });

            // Generate Report Logic
            $("#generate_report_btn").click(function() {
                let subId = $("#subject_select").val();
                if(!subId) return alert("Select a subject");

                $.ajax({
                    url: "ajaxhandler/attendanceAjax.php",
                    type: "POST",
                    data: { action: "get_report", course_id: subId },
                    dataType: "json",
                    success: function(data) {
                        let html = '';
                        data.forEach(row => {
                            let per = row.total_classes > 0 ? ((row.present_count / row.total_classes) * 100).toFixed(1) : 0;
                            let statusColor = per < 70 ? "#ef4444" : "#10b981"; // Red if < 70%
                            let statusText = per < 70 ? "Shortage" : "Eligible";

                            html += `<tr>
                                <td>${row.roll_no}</td>
                                <td>${row.name}</td>
                                <td>${row.present_count}</td>
                                <td>${row.total_classes}</td>
                                <td style="font-weight:bold; color:${statusColor}">${per}%</td>
                                <td style="color:${statusColor}">${statusText}</td>
                            </tr>`;
                        });
                        $("#report_data").html(html);
                        $("#report_area").show();
                        $("#report_title").text($("#subject_select option:selected").text() + " Report");
                    }
                });
            });
        });
    function printReport() {
        // 1. Get the subject name for the filename
        let subject = $("#subject_select option:selected").text();
        let originalTitle = document.title;

        // 2. Set the window title (This becomes the PDF filename)
        document.title = "Attendance_Report_" + subject + "_" + new Date().toLocaleDateString();

        // 3. Trigger Print
        window.print();

        // 4. Restore original title
        document.title = originalTitle;
        }
    </script>
</body>
</html>